version: "3.7"
services:
  panopticon-api:
    build: ./api
    container_name: panopticon-api
    command: /bin/sh -c "rm -f tmp/pids/server.pid && bundle install && rails s -b '0.0.0.0' -p 3000"
    volumes:
      - ./api:/api
    ports:
      - 9900:3000
    depends_on:
      - panopticon-db
  panopticon-db:
    image: mysql:5.7
    container_name: panopticon-db
    environment:
      MYSQL_USER: user
      MYSQL_ROOT_PASSWORD: pass
    ports:
      - 9910:3306
    volumes:
      - ./data/mysql:/var/lib/mysql
  panopticon-front:
    build: ./front
    container_name: panopticon-front
    environment:
      - API_URL=http://localhost:9900
    ports:
      - 9999:3000
  panopticon-bi:
    image: metabase/metabase:latest
    container_name: panopticon-bi
    ports:
      - 9920:3000
    volumes:
      - ./data/metabase:/metabase.db:cached
