version: "3.7"
services:
  panopticon-api:
    build: ./api
    command: /bin/sh -c "rm -f tmp/pids/server.pid && bundle install && rails s -b '0.0.0.0' -p 3000"
    volumes:
      - ./api:/api
    ports:
      - 5000:3000
    depends_on:
      - panopticon-db
  panopticon-db:
    image: mysql:5.7
    environment:
      MYSQL_USER: user
      MYSQL_ROOT_PASSWORD: pass
    ports:
      - 3306:3306
    # TODO volumesの定義
  # TODO Frontの定義
