openapi: 3.0.0
info:
  version: 0.1.0
  title: Panopticon API
servers:
  - url: 'http://localhost:3000'
paths:
  /v1/projects:
    get:
      operationId: projects_get
      summary: List available projects
      responses:
        '200':
          description: Returns a list of projects
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Projects'
components:
  schemas:
    Projects:
      type: array
      items:
        $ref: '#/components/schemas/Project'
    Project:
      type: object
      required:
        - id
        - name
      properties:
        id:
          type: integer
          format: int64
        name:
          type: string
