Projects:
  type: array
  items:
    $ref: "#/components/schemas/Project"
Project:
  type: object
  required:
    - id
    - name
  properties:
    id:
      type: integer
      format: int64
    name:
      type: string
