# Common
MutationResponse:
  type: object
  required:
    - id
  properties:
    id:
      type: integer
      format: int64

# Projects
Projects:
  type: array
  items:
    $ref: "#/components/schemas/ProjectGet"
ProjectGet:
  type: object
  required:
    - id
    - name
  properties:
    id:
      type: integer
      format: int64
    name:
      type: string
ProjectPost:
  type: object
  required:
    - name
  properties:
    name:
      type: string

# Tasks
Tasks:
  type: array
  items:
    $ref: "#/components/schemas/TaskGet"
TaskGet:
  type: object
  required:
    - id
    - name
    - status
  properties:
    id:
      type: integer
      format: int64
    external_url:
      type: string
    name:
      type: string
    description:
      type: string
    status:
      type: string
      enum:
        - created
        - todo
        - doing
        - done
        - closed
TaskPost:
  type: object
  required:
    - name
  properties:
    name:
      type: string
    description:
      type: string
TaskPut:
  type: object
  required:
    - name
    - description
    - status
  properties:
    name:
      type: string
    description:
      type: string
    status:
      type: string
TaskStatusPut:
  type: object
  required:
    - before_status
    - after_status
  properties:
    before_status:
      type: string
      enum:
        - created
        - todo
        - doing
        - done
        - closed
    after_status:
      type: string
        enum:
          - created
          - todo
          - doing
          - done
          - closed
