/v1/projects:
  $ref: "./projects.yaml"
/v1/projects/{project_id}/tasks:
  $ref: "./tasks.yaml"
/v1/projects/{project_id}/tasks/{task_id}:
  $ref: "./tasks_task_id.yaml"
/v1/projects/{project_id}/tasks/{task_id}/status:
  $ref: "./tasks_task_id_status.yaml"
/v1/projects/{project_id}/task_providers:
  $ref: "./task_providers.yaml"
/v1/projects/{project_id}/task_providers/{task_provider_id}:
  $ref: "./task_providers_task_provider_id.yaml"
