get:
  operationId: projects_get
  summary: List available projects
  tags:
    - Projects
  responses:
    "200":
      description: Returns a list of projects
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/Projects"
post:
  operationId: projects_post
  summary: Create project
  tags:
    - Projects
  requestBody:
    content:
      application/json:
        schema:
          $ref: "#/components/schemas/ProjectPost"
  responses:
    "200":
      description: Created project id
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/MutationResponse"
