get:
  operationId: tasks_get
  summary: List tasks
  tags:
    - Tasks
  parameters:
    - in: path
      name: project_id
      description: "プロジェクトID"
      required: true
      schema:
        type: integer
        format: int64
    - in: query
      name: status
      description: "タスクステータス"
      required: false
      schema:
        type: string
        enum:
          - created
          - todo
          - doing
          - done
          - closed
    - in: query
      name: keyword
      description: "検索キーワード"
      required: false
      schema:
        type: string
  responses:
    "200":
      description: Returns a list of tasks
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/Tasks"
