get:
  operationId: tasks_task_id_get
  summary: Show task detail
  tags:
    - Tasks
  parameters:
    - in: path
      name: project_id
      description: "プロジェクトID"
      required: true
      schema:
        type: integer
        format: int64
    - in: path
      name: task_id
      description: "タスクID"
      required: true
      schema:
        type: integer
        format: int64
  responses:
    "200":
      description: Returns a task detail
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/TaskGet"
post:
  operationId: tasks_task_id_post
  summary: Create a task
  tags:
    - Tasks
  requestBody:
    content:
      application/json:
        schema:
          $ref: "#/components/schemas/TaskPost"
  responses:
    "200":
      description: Create a task
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/MutationResponse"
put:
  operationId: tasks_task_id_put
  summary: Modify a task
  tags:
    - Tasks
  requestBody:
    content:
      application/json:
        schema:
          $ref: "#/components/schemas/TaskPut"
  responses:
    "200":
      description: Modify a task
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/MutationResponse"
