version: "3.7"
services:
  panopticon-api:
    stdin_open: true
    tty: true
    build: .
    container_name: api
    command: /bin/sh -c "rm -f tmp/pids/server.pid && bundle install && rails s -b '0.0.0.0' -p 3000"
    volumes:
      - .:/api
    ports:
      - 3000:3000
    depends_on:
      - panopticon-db
  panopticon-db:
    image: mysql:5.7
    environment:
      MYSQL_USER: user
      MYSQL_ROOT_PASSWORD: pass
    ports:
      - 3306:3306
    # volumes:
    #   - mysql_data:/var/lib/mysql
  metabase:
    image: metabase/metabase:latest
    container_name: metabase
    ports:
      - 3300:3000
    volumes:
      - ./docker/metabase/data:/metabase.db:cached
  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    ports:
      - 8888:80
    depends_on:
      - panopticon-db
    links:
      - panopticon-db:panopticon-db
    environment:
      PMA_HOST: "panopticon-db"
      PMA_PORT: 3306
      PMA_USER: root
      PMA_PASSWORD: pass
  swagger-ui:
    image: swaggerapi/swagger-ui
    container_name: swagger-ui
    ports:
      - 8011:8080
    volumes:
      - ./docker/openapi/merged.yaml:/usr/share/nginx/html/merged.yaml
    environment:
      API_URL: merged.yaml
  swagger-merger:
    build: ./docker/swagger-merger
    volumes:
      - ./docker/swagger-merger/watch.js:/watch.js
      - ./docker/openapi:/data
    environment:
      NODE_PATH: /usr/local/lib/node_modules
    entrypoint: node /watch
