name: API CI Excution Action

on:
  push:
    branches:
      - develop
  pull_request:
    branches:
      - develop

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: init docker-compose
        run: make
        working-directory: ./api
      - name: test
        run: make rspec
