name: API CI Excution Action

on:
  push:
    branches:
      - develop
    paths:
      - api/**
      - .github/workflows/api-ci-execute-action.yaml
  pull_request:
    branches:
      - develop
    paths:
      - api/**
      - .github/workflows/api-ci-execute-action.yaml

jobs:
  rspec:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: init docker-compose
        run: make setup-test
        working-directory: ./api
      - name: test
        run: docker-compose exec -T panopticon-api bundle exec rspec
        working-directory: ./api
