name: Jira Cooperation Action

on:
  issues:
    types: [labeled]
  pull_request:
    branches:
      - develop

jobs:
  cooperate-issue:
    if: github.event.label.name == 'loadmap'
    runs-on: ubuntu-latest
    steps:
      - name: Login
        uses: atlassian/gajira-login@master
        env:
          JIRA_BASE_URL: ${{ secrets.JIRA_BASE_URL }}
          JIRA_USER_EMAIL: ${{ secrets.JIRA_USER_EMAIL }}
          JIRA_API_TOKEN: ${{ secrets.JIRA_API_TOKEN }}

      - name: Debug
        run: cat $GITHUB_EVENT_PATH

      - name: Get Cooperated Issue Number
        uses: actions/github-script@v6
        id: get-cooperated-issue-number
        with:
          script: |
            const comments = await github.rest.issues.listComments({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: context.issue.number,
            });
            console.log(comments)
            const targetComment = comments.data.map((data) => data.body).find((body) => /JIRA-ISSUE-NUM=/.test(body))
            if (targetComment) {
              return targetComment.split('=')[1]
            }
            return 'cooperated'

      - name: Create Jira Issue
        id: create-jira-issue
        uses: atlassian/gajira-create@v2.0.1
        # 連携済はスキップ
        if: steps.get-cooperated-issue-number.outputs.result != 'cooperated'
        with:
          # 付けたいチケット名を選択(jiraのAPItokenのlabelに合わせる)
          project: PAN
          # 課題タイプを指定
          issuetype: Task
          # issuesのタイトルが要約になるように設定
          summary: ${{ github.event.issue.title }}
          # issuesの本文が説明になるように設定
          description: ${{ github.event.issue.body }}

      - name: Commnet Issue Number
        uses: actions/github-script@v6
        if: steps.get-cooperated-issue-number.outputs.result != 'cooperated'
        with:
          script: |
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: 'JIRA-ISSUE-NUM=${{ steps.create-jira-issue.outputs.issue }}'
            })
      # - name: コメントつけてみる
      #   uses: actions/github-script@v6
      #   with:
      #     script: |
      #       github.rest.issues.createComment({
      #         issue_number: context.issue.number,
      #         owner: context.repo.owner,
      #         repo: context.repo.repo,
      #         body: '👋 Thanks for reporting!'
      #       })

      # 方針
      # 1. コメントを捜査して、JIRAの紐付けがあるかを検証
      # 2. JIRAの紐付けがあれば、終了
      # 3. なければ、JIRAのチケット登録

      # うわ・・・なんか、Jira側の情報をGitHub上に持っておかないと。。
      # - name: Find Jira Issue
      #   uses: atlassian/gajira-find-issue-key@master
