name: Jira Create Task Action

on:
  issues:
    types: [labeled]

jobs:
  cooperate-issue:
    if: github.event.label.name == 'loadmap'
    runs-on: ubuntu-latest
    steps:
      - name: Login
        uses: atlassian/gajira-login@master
        env:
          JIRA_BASE_URL: ${{ secrets.JIRA_BASE_URL }}
          JIRA_USER_EMAIL: ${{ secrets.JIRA_USER_EMAIL }}
          JIRA_API_TOKEN: ${{ secrets.JIRA_API_TOKEN }}

      - name: Get Cooperated Issue Number
        uses: actions/github-script@v6
        id: get-cooperated-issue-number
        with:
          # デフォルトだとJSONエンコードされる。比較が面倒なので、プレーンな文字列で返すように変更。
          result-encoding: string
          script: |
            const comments = await github.rest.issues.listComments({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: context.issue.number,
            });
            const targetComment = comments.data.map((data) => data.body).find((body) => /JIRA-ISSUE-NUM=/.test(body))
            if (targetComment) {
              return targetComment.split('=')[1]
            }
            return 'not cooperated'

      - name: Convert URL
        id: convert-url
        run: echo '::set-output name=url::https://github.com/yuya-okada527/panopticon/issues/${{ github.event.issue.number }}'

      - name: Create Jira Issue
        id: create-jira-issue
        uses: atlassian/gajira-create@v2.0.1
        # 連携済はスキップ
        if: steps.get-cooperated-issue-number.outputs.result == 'not cooperated'
        with:
          project: PAN
          issuetype: "タスク"
          summary: ${{ github.event.issue.title }}
          # Jira側からGitHubのIssueを参照できるようにしておく
          description: ${{ steps.convert-url.outputs.url }}

      - name: Move Task to In Progress
        uses: atlassian/gajira-transition@master
        if: steps.get-cooperated-issue-number.outputs.result == 'not cooperated'
        with:
          issue: ${{ steps.get-cooperated-issue-number.outputs.result }}
          transition: "進行中"

      - name: Commnet Issue Number
        uses: actions/github-script@v6
        if: steps.get-cooperated-issue-number.outputs.result == 'not cooperated'
        with:
          script: |
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: 'JIRA-ISSUE-NUM=${{ steps.create-jira-issue.outputs.issue }}'
            })
